### ISSUE TITLE
The  Exp Window is keep moving

### ISSUE THREAD

**Issue by buntarou97** [Excrulon/Tree-of-Savior-Lua-Mods#10]
I dont know if the problem is only in my computer or others experience the same problem too, the issue is, everytime i try to move the exp window for example to the top right corner of my screen, it will always return to its default position and im using the latest version of the addons too.

**Comment by Excrulon** [comment]
Press the reset button on the top right of the window once moving it where
you want it to save the position.

**Comment by buntarou97** [comment]
ok, thanks for the quick response dude
