### ISSUE TITLE
Monster HP bar value at its worst

### ISSUE THREAD

**Issue by Crevox** [Excrulon/Tree-of-Savior-Lua-Mods#105]
Dunno what's been happening lately with this :(

-HP value does not update when monster takes damage (non-boss too)
-HP value is often wrong and looking at other monsters nearby
-HP value sometimes becomes some extremely high number (700 million)

![image](https://cloud.githubusercontent.com/assets/6427024/15200683/a2a73fa0-17ae-11e6-955b-ea27e5648c1e.png)

**Comment by Excrulon** [comment]
grab latest monster frames. it should be fixed. you're going to see numbers jump when fighting bosses that have minions around them. the minion (traps and stuff) takes the name of the boss but has different hp. if you don't want it to jump, press ctrl when boss is targeted to lock target.

**Comment by Crevox** [comment]
I just grabbed latest hoping it would fix it, but it didn't. :|

**Comment by Excrulon** [comment]
works fine for me...

when I say latest, I mean the actual source files and not the release. haven't packaged it yet.

**Comment by Crevox** [comment]
I might've only done the package, let me try source.

**Comment by Crevox** [comment]
Alright, that resolved the value not updating. Sorry, thanks. :)
