### ISSUE TITLE
Trouble loading

### ISSUE THREAD

**Issue by spreeo** [Excrulon/Tree-of-Savior-Lua-Mods#106]
On the latest version only the first three addons are loading after clicking "load addons" and after clicking it remains on the screen. After clicking again it does the same thing

**Comment by spreeo** [comment]
Was able to figure it out, sorry

**Comment by Fatuh** [comment]
I have the same problem, what did u do?

**Comment by Excrulon** [comment]
just extract the release zip to tos directory and overwrite everything. that is all.

**Comment by Skaxlol** [comment]
I have the exact same problem. I extracted to tos directory and overwrote everything. It still says first three addons loaded and nothing happens, with the Addons button staying there
