### ISSUE TITLE
Pet stamina display

### ISSUE THREAD

**Issue by laurencee** [Excrulon/Tree-of-Savior-Lua-Mods#107]
For mounted classes they do not get the mount stat bonuses unless their mount has stamina.

When mounted you can't really see the stamina of the pet so ideally we should be able to see the pets stamina easily somewhere on screen at all times (probably like other games with a mini unit frame for the pet).

**Comment by Excrulon** [comment]
not going to implement myself, but someone else is welcome to...

**Comment by Xanaxiel** [comment]
I'll try to get the ball rolling on this as I play a mounted class too
