### ISSUE TITLE
Missing Friendly Duel Request from menus

### ISSUE THREAD

**Issue by Simego** [Excrulon/Tree-of-Savior-Lua-Mods#108]
This option is missing from the ContextMenu, probably need to change in **blockandreport.lua** but i don't know the param to duel, if you give me the coords i can change and publish.

Since i don't know any in-game commands to duel, we can't duel with the addon :smile:

**Comment by Excrulon** [comment]
that's fixed in the latest source if you want to copy it over manually.

**Comment by Simego** [comment]
yeah sorry, i was just checking the commits after the release, sorry for the post
