### ISSUE TITLE
Card lvl 2 calc

### ISSUE THREAD

**Issue by Diolik** [Excrulon/Tree-of-Savior-Lua-Mods#109]
lvl 2 give me more exp then 3 lvl?

![71fd6a3bb03b47451eab62b94922bd03](https://cloud.githubusercontent.com/assets/19318760/15203418/0a419944-181d-11e6-957e-89f4cd219f42.png)

Have last commit [this](https://github.com/Excrulon/Tree-of-Savior-Lua-Mods/commit/050f935ffb73fd9d8595fcedf5643164c516120f)

**Comment by Excrulon** [comment]
Ahhh stupid mistake. I know the fix, sec.

**Comment by Excrulon** [comment]
1b1cd19a9932c3030c8a4d3ab95903e9b3554c93 should fix it.

**Comment by Crevox** [comment]
Fixed the bottom, but it didn't fix the top.

![image](https://cloud.githubusercontent.com/assets/6427024/15204383/4df01a1c-17d2-11e6-9a58-bd3b1acffc5c.png)

**Comment by Excrulon** [comment]
oy, didn't say it did...

**Comment by Crevox** [comment]
I know, just making sure you know. :) Not sure if this fits this issue, as the topic and description are very vague.

**Comment by Excrulon** [comment]
try 2edf9dd17927deab90ab9420bf58187db3257fe9.

matches my hand calculation perfectly.

**Comment by Crevox** [comment]
:+1: 

![image](https://cloud.githubusercontent.com/assets/6427024/15204667/78a13ac2-17d5-11e6-942a-6c05c1271cf5.png)
