### ISSUE TITLE
Load Button Problem

### ISSUE THREAD

**Issue by Calamax** [Excrulon/Tree-of-Savior-Lua-Mods#112]
When I click the upload button it does not disappear and does not carry many addons. I looked for a solution here but not found. Is there anything I can try?

**Comment by Zargof** [comment]
Same problem here. I downloaded the .zip file, pasted it to my Tree of Savior folder [C:\Program Files\Steam\steamapps\common\TreeOfSavior], then I ran the game, I click the "Load Addons" button and a message pops up saying "Better Quest loaded!, Channel Surfer loaded!, Context menu additions loaded!" but nothing appears.

**Comment by Excrulon** [comment]
Make sure the unicode is in the filename for the ipf like it is here.

https://github.com/Excrulon/Tree-of-Savior-Lua-Mods/blob/master/data/☃expcardcalculator.ipf

Sometimes the unzip program people use removes or corrupts those characters.

**Comment by Zargof** [comment]
Does this mean it's corrupted?
![screenshot_15](https://cloud.githubusercontent.com/assets/19328725/15238315/1d1fce3a-1883-11e6-8ade-b613a4b861d3.png)

**Comment by Excrulon** [comment]
just erase those bad characters and replace it with ☃ instead. should work.

stupid zip programs not handling unicode.

**Comment by Zargof** [comment]
Oh cool, I used 7-zip to extract the files and replaced the ones I used earlier. Now it's completely working, thanks man!
