### ISSUE TITLE
data\Xexpcardcalculator.ipf file name uni code issue

### ISSUE THREAD

**Issue by g4bb4j03** [Excrulon/Tree-of-Savior-Lua-Mods#113]
Hi the file name for the expcardcalculator.ipf has a very odd symbol in front for me. I need to use 7zip to get it with the symbol ☃ in front extracted. You maybe consider to not use such a kind of uni code symbol in the file name in the future.

**Comment by Excrulon** [comment]
I know. Have to use unicode. Just rename it to have unicode if your zip
program messes it up and all is well.
