### ISSUE TITLE
Summon HP incorrect; changes values based on current target

### ISSUE THREAD

**Issue by Hereticide** [Excrulon/Tree-of-Savior-Lua-Mods#114]
Summon appears to wildly change HP values depending on what is targeted at the time or last attacked. Video example. At the end of the video you will note the 700+ million HP which doesn't follow the assumption of adopting target's HP values so something else may be afoot as well.

Please ignore my horrible play as I was focused on the Summon HP bar at the top the entire time to see if I could spot what was happening accurately lol

https://youtu.be/ZFM1gbzMdj0

**Comment by Excrulon** [comment]
Not a clue what causes this yet. but on the bright side at least we can see HP period for now.

**Comment by Hereticide** [comment]
So very true xD Every issue only helps it get better so I'm perfectly fine with finding small things. My Summon's HP bar works by default so the issue doesn't interrupt game play =)

I hope the last part of your comment isn't foreshadowing =/

**Comment by Excrulon** [comment]
387f6ecd9cbb96fd0b6e10c9df15f91eac35e1f2
