### ISSUE TITLE
Duel buttom disappears

### ISSUE THREAD

**Issue by biaachan** [Excrulon/Tree-of-Savior-Lua-Mods#115]
Hi!

I found a issue that appeared after the last update. The button "request duel" that existed, now disappeared (I think it was replaced with the buttom "block and report", because there's the new buttom and a buttom "block player").

Me and my friend that own the updated addons have ths issue :)
Thanks in advance!

**Comment by Excrulon** [comment]
Download the latest version release last night. should be in there.

**Comment by biaachan** [comment]
Oh thanks! I'll donwload it and test. Thanks <3
