### ISSUE TITLE
White Square

### ISSUE THREAD

**Issue by xator91** [Excrulon/Tree-of-Savior-Lua-Mods#12]
Orange Sakmoli, show a white square instead of "element, race" etc..

**Comment by Excrulon** [comment]
Thanks, will look into it. If I'm ever of level to find/kill that mob!

**Comment by xator91** [comment]
Map "Gytis Settlement Area" it's near 69

**Comment by Excrulon** [comment]
Fixed in recent commit, will be in next release.
