### ISSUE TITLE
Character stuck in loading screen

### ISSUE THREAD

**Issue by Kaisertyrant** [Excrulon/Tree-of-Savior-Lua-Mods#121]
Hiya ive been using this mod for awhile. But today i decided to try download the tooltiphelper and classicchat addon. After downloading them, I tried using a statue to teleport to an area and I keep getting stuck in loading screen(loads 2/3 bar)and im unable to get myself unstuck now. I was wondering if its a compatibility issue or is it just me? thanks.

**Comment by Excrulon** [comment]
Don't see it having anything to do with addons.

**Comment by Kaisertyrant** [comment]
ok thanks. i guess i'll only stay with this addon in the meantime.
