### ISSUE TITLE
I cant put other addons

### ISSUE THREAD

**Issue by Greedys** [Excrulon/Tree-of-Savior-Lua-Mods#124]
Hello, i want to use the tooltiphelper addon from other guy, and i cant use it, u put the dofile in addonloader.lua and doesnt work :(

**Comment by Xanaxiel** [comment]
Hey man, it's already in the instructions, if you used @Excrulon's pack you gotta add the dofile line on the addonloader.lua

**Comment by Greedys** [comment]
I do that and doesnt work men

**Comment by Greedys** [comment]
--[[ADDONS]]

dofile("../addons/mapfogviewer/mapfogviewer.lua");
dofile("../addons/monsterframes/monsterframes.lua");
dofile("../addons/monstertracker/monstertracker.lua");
dofile("../addons/tooltiphelper/tooltiphelper.lua");

And the "load addons dont read that"

**Comment by tanjunior** [comment]
is the "tooltiphelper" in the "addons" folder?

**Comment by Greedys** [comment]
Yes

**Comment by Greedys** [comment]
![image](https://cloud.githubusercontent.com/assets/19364005/15271133/34e59ce0-1a11-11e6-823c-afe3dabc5239.png)[/image]

**Comment by Greedys** [comment]
But the others two addons i put doesnt work

**Comment by Greedys** [comment]
I download the last version and it works.

**Comment by Xanaxiel** [comment]
Can be [closed](https://github.com/Xanaxiel/ToS-Addons/issues/2)

**Comment by Greedys** [comment]
@Xanaxiel  Man, i cant disable the exp viewer can you help me with that?

What i need to delete in this (If i delete all, the load addons dont start, and if i write something inside that dofile, doesnt work)

dofile("../addons/expviewer/expviewer.lua")

**Comment by tanjunior** [comment]
show your addon folder and addonloader.lua file
