### ISSUE TITLE
Lag on low profile laptop on dungeons.

### ISSUE THREAD

**Issue by s1lv3rw0lf** [Excrulon/Tree-of-Savior-Lua-Mods#125]
Hello, my friend tried the addons today and it runs without problem on any normal map. But on the lvl 50 dungeon the lag increases to unplayable amounts, even DCing.

Is there any specific addon that may be causing this severe lag on dungeons? Any help or suggestion on how to hunt down the troublesome addon is welcome :D

**Comment by Excrulon** [comment]
Nothing I can help with. addons aren't much of a performance hit.
