### ISSUE TITLE
I cant disable addons

### ISSUE THREAD

**Issue by Greedys** [Excrulon/Tree-of-Savior-Lua-Mods#127]
I try deleting the dofiles, but if i do that i cant load any addons, can you help me plz or being more especific plz.

**Comment by Kamatis** [comment]
did you delete the
`dofile("../addons/utility.lua");`
line? it's a dependency.

**Comment by Greedys** [comment]
Nope, i have to delete that?

**Comment by Greedys** [comment]
Now i delete 
dofile("../addons/expviewer/expviewer.lua")

Now i can delete any other addon?

**Comment by Kamatis** [comment]
Nope. You should NOT delete it. I just asked since it might be the problem.

**Comment by Greedys** [comment]
Ahh, nope, i dont delete that, i just want to delete 
dofile("../addons/expviewer/expviewer.lua"); that

**Comment by Greedys** [comment]
The only thing i need to do is delete two addons, but if i delete this 
dofile("../addons/expviewer/expviewer.lua"); 

All colapses and i cant use any addons.

**Comment by Greedys** [comment]
@Excrulon help plz

**Comment by TehSeph** [comment]
You can't remove the expviewer. It's frame is built into the `SumApi.ipf` file that is required for the entire addonloader to work.

**Comment by tanjunior** [comment]
this is what my addons looks like, and it works.
--[[ADDONS]]
dofile("../addons/betterquest/betterquest.lua");
dofile("../addons/channelsurfer/channelsurfer.lua");
dofile("../addons/contextmenuadditions/contextmenuadditions.lua");
dofile("../addons/expcardcalculator/expcardcalculator.lua");
--dofile("../addons/expviewer/expviewer.lua");
--dofile("../addons/guildmates/guildmates.lua");
dofile("../addons/hidemaxedattributes/hidemaxedattributes.lua");
dofile("../addons/mapfogviewer/mapfogviewer.lua");
dofile("../addons/monsterframes/monsterframes.lua");
dofile("../addons/monstertracker/monstertracker.lua");
dofile("../addons/showinvestedstatpoints/showinvestedstatpoints.lua");
dofile("../addons//tooltiphelper/tooltiphelper.lua");

**Comment by Excrulon** [comment]
should be fixed when I break out the expviewer into its own ipf.
