### ISSUE TITLE
Expviewer

### ISSUE THREAD

**Issue by akiira7** [Excrulon/Tree-of-Savior-Lua-Mods#128]
the exp viewer, don't stay on the place i put, it's keep going for the middle of the screen no matter what i do or where i put

**Comment by TehSeph** [comment]
> Be sure to press the "R" button at the topright of the experience viewer window in order to save its position after moving it. It will move back if you don't.

**Comment by akiira7** [comment]
Thanks, i will try it

**Comment by akiira7** [comment]
it works, thanks, but beffore i don't need to do this, the exp viewer just stay wherever i put
