### ISSUE TITLE
no addon button upon login

### ISSUE THREAD

**Issue by greyradish** [Excrulon/Tree-of-Savior-Lua-Mods#129]
When I log in there isnt an addon button display to click on.

I followed the instructions and added the files to the tos folder. I looked in each folder to make sure each file matched the original. I even looked at videos of mod instillation to see if I missed anything.

**Comment by TehSeph** [comment]
You've placed `SumAni.ipf` in the data folder and let it overwrite?

**Comment by greyradish** [comment]
Yes it is in the data folder. I did'nt get a message about letting it overwrite.

Here is a picture of the folder 
https://drive.google.com/open?id=0B6sFHzjBVSYZcVlSa0dmSDloTWs

**Comment by LeoLombardi** [comment]
@greyradish If I remember correctly the SumAni.ipf file that allows for external load is 4KiB, and the one on your screenshot is 2KiB - I suppose it is the original SumAni.ipf. Try re-downloading and overwriting again.

**Comment by greyradish** [comment]
That did the trick!

Thank you!!!

**Comment by LeoLombardi** [comment]
Always a pleasure, glad it worked. =)
