### ISSUE TITLE
Hey bro I made you an uninstaller

### ISSUE THREAD

**Issue by lukeizcool** [Excrulon/Tree-of-Savior-Lua-Mods#13]
[Uninstall TOS addons.zip](https://github.com/Excrulon/Tree-of-Savior-Lua-Mods/files/216254/Uninstall.TOS.addons.zip)

lul

**Comment by welj** [comment]
if my steam have dir D:\Steam ?

**Comment by Excrulon** [comment]
This isn't really an issue. May have an addon manager soon that'll do this but I guess others can use a batch script if they want.
