### ISSUE TITLE
contribute - Multi Languages

### ISSUE THREAD

**Issue by marclfv** [Excrulon/Tree-of-Savior-Lua-Mods#132]
Hi @Excrulon 

I would like to contribute a version that could have other languages.

However, I am unsure of how to organize the language file.

The idea would be to have a combo box to select the language and the button "Load Addons".

As you format the language file?
User _G [ 'variable'] or #define?

**Comment by Excrulon** [comment]
I'm not really interested in spending any time on this (not much language in these anyway...) but if you come up with something good for it I may take a PR.
