### ISSUE TITLE
Map viewer shows out of bounds unexplored area

### ISSUE THREAD

**Issue by Spectro** [Excrulon/Tree-of-Savior-Lua-Mods#137]
Here's an example: http://images.akamai.steamusercontent.com/ugc/448484556135340082/457C5478766129497382696A68476FEA8C865E00/

**Comment by Excrulon** [comment]
That's not a bug. Just part of the map. And you can get there. It's a
secret! Try to figure it out without looking it up!

**Comment by Spectro** [comment]
Thanks for the reply. I would have never guessed there was a secret area on that map.
