### ISSUE TITLE
Request: Market - Queuing Time for the Sell tab

### ISSUE THREAD

**Issue by Nyuha** [Excrulon/Tree-of-Savior-Lua-Mods#141]
Would be cool to know when the item sell time will expire, would be a shame if i go Sleep and the selling time is about to expire in 5 minutes.

![queing retrieve](https://cloud.githubusercontent.com/assets/13547660/15452137/37979692-1fba-11e6-8c6b-8731e919dba0.png)

![pls](https://cloud.githubusercontent.com/assets/13547660/15452138/39e73ab0-1fba-11e6-8612-8b7073ab743e.png)

TY!

**Comment by Excrulon** [comment]
I doubt I'll ever do this...
