### ISSUE TITLE
Sugestion: Improvements to choose targets

### ISSUE THREAD

**Issue by harununes** [Excrulon/Tree-of-Savior-Lua-Mods#146]
Hello! I'm playing using keyboard, my char is elementalist C3, when many monsters or appear depending on the map, the target to settle some skills . Is there any way or issue for better targeting of display to use spells ? Ex: Frost Cloud, Hail and more.
Thanks for help!

**Comment by WillTheDoggy** [comment]
AYYYYYYYYYYYYYYYYYYYYYYYY

**Comment by Excrulon** [comment]
No idea... you should try making something for this if you want.

**Comment by xpaperjamx** [comment]
sir excrulon is there a way to change mobs color name?

**Comment by harununes** [comment]
Is there any way to change the Target Skill icon for something more visible ? Set on the keyboard depending on the map and the amount of monsters and animations of other skills , it is difficult to target the skill.
[http://i.imgur.com/XwwT75R.jpg](url)

**Comment by Excrulon** [comment]
you guys can make that stuff.

**Comment by harununes** [comment]
Sorry, but I do not know about programming and creating addons :(

**Comment by xpaperjamx** [comment]
sir excrulon i got experience how coding works, but i dont know how to pull out correct declared variables of the game like:

local isSit = control.IsRestSit(); <-- how did u get it sir?
local invItemList = session.GetInvItemList(); <-- inventory?
local stat = info.GetStat(session.GetMyHandle());<--- stat hp?

where i could see all declared variables of the which game uses. pls enlighten me sir.. tnx
