### ISSUE TITLE
Binary SumAni.ipf

### ISSUE THREAD

**Issue by diraven** [Excrulon/Tree-of-Savior-Lua-Mods#15]
Just a quick question - what is this file and what does it do? It's binary and it replaces one of the game files, so I'm just curious and cautious.

Can you please explain?

I'd probably like to do some addons myself, but would like to figure this out first.

**Comment by Excrulon** [comment]
This isn't an issue. ;)

ipf is just how the game packs files. SumAni is how I choose to distribute my addons.

**Comment by ezcloudllc** [comment]
For anyone with the same question I had here is a decent explanation: https://github.com/Tree-of-Savior-Addon-Community/Addon-Tutorial/wiki

**Comment by diraven** [comment]
For anyone with the same question I had here is a decent explanation: https://github.com/Tree-of-Savior-Addon-Community/Addon-Tutorial/wiki
