### ISSUE TITLE
expcardcalculator 

### ISSUE THREAD

**Issue by Tonisuka** [Excrulon/Tree-of-Savior-Lua-Mods#151]
How can I hide the expcardcalculator menu in the main window?
I've already comment it in the addonloader.lua file but it doesn't seem to work.
![untitled](https://cloud.githubusercontent.com/assets/19605984/15602835/a1807f36-2421-11e6-88a4-9aee4a59079e.png)

**Comment by vincentraulic** [comment]
Remove the ipf file

**Comment by Tonisuka** [comment]
wow that simple. lot of thx vincentraulic  XD
