### ISSUE TITLE
Zoomy doesn't work???

### ISSUE THREAD

**Issue by Marylain** [Excrulon/Tree-of-Savior-Lua-Mods#154]
Hello!
In installed the add-on following all the instructions.
Everything seems to work properly (monter count, exp viewer and so on...) EXCEPT the Zoomy.
I pressed left ALT and + at the same time, but nothing happens.
The same for left ALT -
What am I supposed to do?

Thanks.

**Comment by Grillo-del-mal** [comment]
sometimes your keyboard locale makes those keys to change, try the keys between '0' and 'backspace'

**Comment by Excrulon** [comment]
Did you press the +/- keys beside the backspace key and not the one on the numpad? Are you sure you downloaded the ipf version of it and put the proper unicode character in the filename?

**Comment by Marylain** [comment]
Grillo thank you so much!!!
In my keyboard + and - are, actually ? and ^ that are the Keys between 0 and backspace.

Solved! ^^

**Comment by Excrulon** [comment]
No love for me? Sniffles.

glad it works. Need to figure out a way to normalize keybindings between all different locales I guess.

**Comment by Marylain** [comment]
Ahahahaha!
Sorry Excurlon!

Thank you! :***
