### ISSUE TITLE
IPF vs LUA files

### ISSUE THREAD

**Issue by zckrs** [Excrulon/Tree-of-Savior-Lua-Mods#157]
Hi,

I'm curious about why you prefer IPF file to share addons ?

What are advantage and drawbacks ?

**Comment by Excrulon** [comment]
Self contained, less chances of installation going wrong, no annoying addon loaders, etc.

**Comment by zckrs** [comment]
Understood :-)

**Comment by ShyPixie** [comment]
But this is a terrible security breach, mainly because your commits are not digitally signed. If someone infect your files and make a commit to your git of a IPF with malicious code, no one will be able to read the code unless the user decrypt, extract, etc.

**Comment by Excrulon** [comment]
Uhh who cares? It's a video game. The same thing could happen with just lua files.

**Comment by TehSeph** [comment]
lol yep because all addon devs are malicious hackers. ggwp

**Comment by Miei** [comment]
FYI there's also some functionality that we can't use without packing an IPF, mainly `RegisterMsg()`

**Comment by TehSeph** [comment]
For the record, no smart dev is going to accept a pull request from anyone that just contains a new ipf file with no source code, and most of us don't even keep ipfs on the repo and build our releases each time.
