### ISSUE TITLE
Implement world boss

### ISSUE THREAD

**Issue by xator91** [Excrulon/Tree-of-Savior-Lua-Mods#18]
Can you implement a world boss timer or world boss list? Or something to alert you, when someone write in shout "World Boss"?

**Comment by Spl3en** [comment]
I don't think it would be a good idea, as it would give you an advantage over those who don't use the plugin. We probably don't want people to start complaining about players "cheating" with plugins.

**Comment by Excrulon** [comment]
It's not possible to automate it since respawn times are server side. No
desire to program a manual timer. Besides, there are tons of existing timer
apps you can use already.

**Comment by dizolexx** [comment]
well i think u could create an addon that track the boss kill when someone using the addon killed it and update the time tracker for all other users. don't know if IMC would allow it tho, but i don't think it would be unfair, it's just an automated community information trading. All plugins and addons give the user some kind of advantage.
Also havo no idea on how hard would be to do that kind of application.
