### ISSUE TITLE
Damage Viewer

### ISSUE THREAD

**Issue by xator91** [Excrulon/Tree-of-Savior-Lua-Mods#19]
Can you implement a damage viewer chat, so we can see our DPS over time?

**Comment by Excrulon** [comment]
I've been researching this on and off for a couple months. Right now, I
think there's around a 40% chance it's possible to do natively. I'll
definitely implement it given my theories pan out. If not, oh well.

**Comment by ramoncosta** [comment]
Yes plz, this is the best thing you could make right now.
