### ISSUE TITLE
World Map is missing

### ISSUE THREAD

**Issue by Ekey** [Excrulon/Tree-of-Savior-Lua-Mods#23]
Hi. After installing your addons world map for now is missing. Posible to fix? :)
http://i.imgur.com/JMznejn.jpg

Thanks advance!

**Comment by welj** [comment]
close and open client again

**Comment by Excrulon** [comment]
I don't think this could have anything to do with my addons.

**Comment by Ekey** [comment]
@welj - Thanks! It works! :)
