### ISSUE TITLE
Monster kills required text

### ISSUE THREAD

**Issue by fpcompany1** [Excrulon/Tree-of-Savior-Lua-Mods#25]
Maybe its better to display kills/required info under each mob's hp bar?

**Comment by Excrulon** [comment]
Yeah I'll be doing both. I have that implemented it's just ugly. Gonna work on making it prettier.

**Comment by rxsprer** [comment]
Hey, Excrulon, about this, some monsters with the longer names tend to push the rest of the notification out of the screen. It's very neat though, I like it a lot. I like the MOB info and the values on top of their HP UI too, but I do notice that sometimes, the Monster Element Icon tends to mix with the Monster Size Icon. Thank you for all of these though, keep making them look more pimp each update, you are very important to us all!! Is there gonna be an update soon where we get to see that the mob are weak against?
