### ISSUE TITLE
Monster kill completion spam

### ISSUE THREAD

**Issue by Spl3en** [Excrulon/Tree-of-Savior-Lua-Mods#28]
Once a monster kill requirement is completed, the client is flooded by completion system messages : 
![ss](http://puu.sh/olvAZ/c153ee5316.jpg)

We need to add a condition to check if the message hasn't already been displayed : 
 `if (monsterKill == monsterKillCompletion && !messageAlreadyDisplayed)`.

**Comment by TehSeph** [comment]
Already been mentioned [here](https://github.com/Excrulon/Tree-of-Savior-Lua-Mods/commit/87976f0a2c776461c90be40e2933259fed2bb50a#diff-2d5eaac45c1c9122f16cd2eeb2dbaa35L15). :)

**Comment by Excrulon** [comment]
Fixed in 17de8cfaff2f5d71c33238d1b7d9c8e76c952ce0.
