### ISSUE TITLE
More documentations for more contributions

### ISSUE THREAD

**Issue by zckrs** [Excrulon/Tree-of-Savior-Lua-Mods#32]
Hi @Excrulon,

I am very interested to contribute to this repo but I hardly find information on the functioning of LUA plugins with ToS.

* What contains IPF file? How to read them?
* Where do you find global variable like `ui`, `session` and the related function `getFrame`, `SysMsg`?
* How do you inject your LUA file in client ? by `data/SumAni.ipf`?

**Comment by cyrilpangilinan** [comment]
You can find the IPFBrowser [here](https://github.com/Excrulon/IPFBrowser)

The [ToSDev API](https://github.com/Excrulon/TOSdev-API/tree/master/core) contains utils too that can get you started.

**Comment by Excrulon** [comment]
Stuff like that is coming soon, I'll post stuff about it when it is.

**Comment by zckrs** [comment]
Waiting impatiently :smirk_cat:
