### ISSUE TITLE
expviewer keeps reseting position

### ISSUE THREAD

**Issue by pedrosotero** [Excrulon/Tree-of-Savior-Lua-Mods#36]
When i move the expviewer then atack/skill he keeps reseting position to bottom center of screen, dont know if it is just me

**Comment by TehSeph** [comment]
Did you click the `R` in the corner after moving it?

**Comment by pedrosotero** [comment]
R seens to solve this problem, should report that for others

**Comment by Excrulon** [comment]
I've said it a thousand times. It's in the instructions and it's in the post I made about the addons.

Anyway, trying to get a drag and drop callback working for the next version.
