### ISSUE TITLE
Conflict with Quests

### ISSUE THREAD

**Issue by gonkyouka** [Excrulon/Tree-of-Savior-Lua-Mods#38]
There seems to be a conflict between this add-on and the quests:

Secret of the Destroyed Altar (Altar Way)
Search Scouts under Attack (Dvasia Peak)

The add-on makes the client unresponsive. I can confirm that changing channels won't help but instead manually unloading the add-on i.e. by restarting the client and finish the quest before loading add-on.

**Comment by Excrulon** [comment]
I can't see how any of these addons could cause that but if I ever do those quests I guess we'll see if it freezes the game for me.

**Comment by TehSeph** [comment]
I'll be doing Dvasia Peak in < 24hrs from now. Not sure how far off the other quest is, but I can at least partial confirm/deny this when I've reached/completed Search Scouts under Attack if you'd like someone to confirm this.

**Comment by TehSeph** [comment]
Whoops forgot to confirm/deny this, and I don't remember now what happened. Sorry. :|

**Comment by Excrulon** [comment]
I don't think it's really an issue.

**Comment by gonkyouka** [comment]
I encounter another quest which I forgot already but  I guess its not an issue anymore. People should just relog and redo quest again without activating the addon. 

Thanks Excrulon!

**Comment by Excrulon** [comment]
Well there haven't been any other reports with over 35k downloads so that's
the only reason I think it's not related. If someone else can reproduce it
then I'll look at it.
