### ISSUE TITLE
Addon availability for other ToS server (non steam)

### ISSUE THREAD

**Issue by Allecrast** [Excrulon/Tree-of-Savior-Lua-Mods#41]
Hello there, is it possible for you to modify the addon to support other ToS server?

Long story short, few days ago Steam prohibit my country (Indonesia) from playing ToS, the reason is there will be a new ToS server in my region (close beta starting today), therefore Steam stopped the access from Indonesia.

I've been playing the Steam-ToS for a few weeks and been using your extremely useful addon the whole time. I've tried to install the addon for this Indo-ToS, but the client seems unable to detect it.

If you can help us(ToS fans from Indo) that would be very appreciated! Thanks a lot!

P.S I don't know anywhere else to leave you message on this issue, hope this is the right place!

**Comment by Excrulon** [comment]
I have no way to look at this, really. I don't understand why it wouldn't work. Maybe someone else playing on that version can look into it.

**Comment by Allecrast** [comment]
Hmm, okay I'll try to contact the staff about this since it's seems the addon compatibility is not the problem, Thanks for the prompt reply!

**Comment by Excrulon** [comment]
I doubt the staff will do anything for a third party addon.
