### ISSUE TITLE
something important

### ISSUE THREAD

**Issue by Redd1sh** [Excrulon/Tree-of-Savior-Lua-Mods#44]
hello, I'm red from Indonesia
I'm very interesting with your addons since the first time you post it
may I modified your addons? (actually I didnt edit anything, I will email you the detail if you want)
so I can use it in our local server for personal use only
send me an email to redha.ashadi.09@gmail.com
I will sent you an in-game screenshot and detail
thanks a lot for everything, I learn a lot from you
and sorry for my bad english :)

**Comment by pedrobj** [comment]
@Redd1sh You can simply fork it, and make your own updates, then it can be pulled to this main repository by @Excrulon and help everyone o/

**Comment by Redd1sh** [comment]
@pedrobj wow nice, but I never intend to make it public, maybe if @Excrulon want I will post it to you guys
I just need a permission to modify it for personal use in local server

here is the screenshot, Indonesia server
not many people playing because it is still 9 AM and CBT2
![screenshot_20160424_00001](https://cloud.githubusercontent.com/assets/18625059/14765159/67beb47a-09ff-11e6-83b9-7858f5b28896.jpg)
![screenshot_20160424_00002](https://cloud.githubusercontent.com/assets/18625059/14765162/72b32578-09ff-11e6-9d39-86e8cb0b0cf6.jpg)

**Comment by Excrulon** [comment]
Changing what? I can't really stop anyone from modifying it as they want. I just don't really want my mods being distributed anywhere besides on my github. You can make pull requests for valid changes if you want.

**Comment by Redd1sh** [comment]
@Excrulon actually I just copy some stuff from the client, you know which one :p 
but I didn't know if the same method will work when the server is open for public
I will send you a message later

I just planning to change the interface language to Indonesia, since my little brother playing in the same PC with me

nah, it's okay
like I said before, for personal use only, you can have my words
you make it for steam server, and it is not easy stuff to do
and because I scared that people in my country will just share it without the original link

at least here is my gratitude for you guys that make this add ons
thanks a lot for your hardwork, not every people can do something like you guys do

**Comment by cyrilpangilinan** [comment]
I'm not really sure too if you can easily change the localization as some frames are mapped to other referenced *.xmls that have the Korean characters mapped to the templates. Also not sure if there's a decoder of some sort or they just convert it from EUC-KR to UTF-8 after referencing, as I've tried parsing the other *.ies files and even when the data's converted to EUC-KR encoding, other characters come up as question marks or boxes. Haven't spent extra time reading up the code though, maybe there is/isn't.

**Comment by Redd1sh** [comment]
@cyrilpangilinan thanks
yeah that will be a big problem :(
but I will give it a try when I have free time, still busy with my study (I need like 25 hour a day or more please)

**Comment by Excrulon** [comment]
Just modify the text inside the lua file if you really want to change the language.

```lua
xPosition = UPDATE_CELL(
	i,
	richText,
	"{@st41}{s18}Current / Required",
	settings.showCurrentRequiredExperience,
	xPosition,
	yPosition,
	columnKey
);
```

For example, just change "Current / Required" to whatever it is in your language. Do the same for the other fields.
