### ISSUE TITLE
Class Level cap - undefined behavior / wrong values

### ISSUE THREAD

**Issue by rafaelfillipesilva** [Excrulon/Tree-of-Savior-Lua-Mods#45]
Hi!

I and some friends noticed that after the level cap the counter doesn't show the right values but some random numbers/letters in the % field:

Screenshot:
http://i.imgur.com/kIPIwb2.png

**Comment by Excrulon** [comment]
Yeah, not really concerned about that though sicne it doesn't matter at that point.
