### ISSUE TITLE
'Load Addons' button does not appear

### ISSUE THREAD

**Issue by inter5tella** [Excrulon/Tree-of-Savior-Lua-Mods#46]
Hi there,

great work for what i can already see in videos and screenshots. Very helpful for such sort of game.
Unfortunately, i can't get it working :(
I've tested it with the last stable release and the latest git master archive, but the addon loader didn't appear after login (in-game, not just the character selection).

View of my ToS folder:

![ToS folder](https://cloud.githubusercontent.com/assets/12923644/14770584/53ffca48-0a75-11e6-91a0-32062b36078a.JPG)

View of my addons folder:

![addons folder](https://cloud.githubusercontent.com/assets/12923644/14770585/596909ea-0a75-11e6-97c3-e0b642dee2a0.JPG)

Things i've also tried:
- whitelist the file on my AV application
- Unlock the file, as windows told me that it may be blocked as it's from a different computer

The same problem goes with the addon loader from [cwFarmed from fiote](https://github.com/fiote/treeofsavior-addons).

I've also restored the untouched SumAni.ipf after switching from stable to latest Git version.

Thanks for any help.

**Comment by Excrulon** [comment]
You probably didn't overwrite SumAni.ipf in the data folder with the one in
my zip file.

**Comment by inter5tella** [comment]
Is it still needed, as i can't see it in the git file list?
It's also not included in cwLibrary..

**Comment by Excrulon** [comment]
It's definitely in the download. https://github.com/Excrulon/Tree-of-Savior-Lua-Mods/releases/download/1.7/tos-lua-addons-excrulon-20160411-02.zip

**Comment by inter5tella** [comment]
Thanks a lot.
I've found it already in the latest archiv release but was just wondering why it's no more listed at the filelist on the branch frontpage.
Maybe i just overlooked it. It's working now for, many thx to you Excrulon.

**Comment by Excrulon** [comment]
SumAni.ipf has never been committed to the repo.

Glad it works now.
