### ISSUE TITLE
Monster HP doesn't work with bosses

### ISSUE THREAD

**Issue by hieiiganashi** [Excrulon/Tree-of-Savior-Lua-Mods#47]
While trying to do the daily missions, the bosses HP didn't shown up.

**Comment by fiote** [comment]
I don't think bosses have an ingame-wiki with their HPs.

**Comment by Excrulon** [comment]
It's in the game. I'll have this fixed in next release. Should be a pretty huge release soon I hope.

**Comment by Excrulon** [comment]
Will look something like this. Still have a little more to add and clean up.

![Preview](http://i.imgur.com/QAnmHTo.jpg)

**Comment by Excrulon** [comment]
ccfa6a24a9b9d2edd142d0ca598a9b3f020c441c
