### ISSUE TITLE
Monster Kill Counter

### ISSUE THREAD

**Issue by melossequel** [Excrulon/Tree-of-Savior-Lua-Mods#52]
Hi, currently the monster kill tracker does not seem to trigger on certain skills such as heal, cure, and effigy. Thank you for your time and hard work. :)

**Comment by TehSeph** [comment]
I believe this is already fixed on the repo, just not in the releases.

**Comment by Excrulon** [comment]
Yeah, it is. I need to release it already but I have a ton of stuff I'm
trying to finish up for it.

**Comment by melossequel** [comment]
Oh! I should have looked more carefully. I'm using the updated version now. Thanks so much for letting me know!
