### ISSUE TITLE
showInvestedStatPoints

### ISSUE THREAD

**Issue by Wolf1030** [Excrulon/Tree-of-Savior-Lua-Mods#55]
Not seeing this anywhere taking affect, Have reinstalled and reloaded the addon several times throughout my play sessions, not seeing where it shows the addon at play,

**Comment by Excrulon** [comment]
It's not officially bundled in the release download yet. You'll have to
grab the file yourself manually and add a line to load it in
addonloader.lua.

**Comment by Wolf1030** [comment]
I am also using Fiotes addons's with his addonloader.lua which loads his and yours just fine with no issues as he has made it load everything thats lua file extensions in the addon folders, yet this particular one has yet to work even with your addon and adding the append line. Where is it suppose to show exactly?

**Comment by Excrulon** [comment]
believe it shows at the bottom of the stats when you scroll all the way
down.

**Comment by zckrs** [comment]
https://github.com/Excrulon/Tree-of-Savior-Lua-Mods/pull/35#issuecomment-212530456

**Comment by Wolf1030** [comment]
Ah you are correct sir, it loaded just fine then, I was so confused as to where it would show I didn't even think to try scrolling down in that window. Thanks for the clarification, should add that to your instructions page.

**Comment by Excrulon** [comment]
Glad it works. When you code nonstop for almost your whole life your brain just thinks in code! :)
