### ISSUE TITLE
Mapfogviewer Broke.

### ISSUE THREAD

**Issue by Wolf1030** [Excrulon/Tree-of-Savior-Lua-Mods#60]
I saw there was an update early this morning to TOS and you also had a update to the MapFogViewer, It was working all savy last night along with another Addon Authors mini map fog [viewer](https://github.com/Maytch/ToS_MiniMapExtra) till I got on a bit ago. I added and removed addon's to narrow it down(one by one,restarted client and used /reload method). 
Your's and his do not load and cause the loader to get stuck/not complete. One I removed both, I did one at a time first, the loader didn't get stuck. So something changed that's causing them to not load. properly. I will be passing this on to @Maytch as well.

**Comment by TehSeph** [comment]
Newest version has been working fine for me. :S

**Comment by Excrulon** [comment]
It works fine on its own. I can't help it if people are using other addons
that hook the same functions (guessing that might be the problem).
Hopefully I can solve that when I finish core api that has a hook method
that everyone should use to be able to hook the same thing along with addon
manager.

To fix it for now, don't use two mods that do the same thing... just pick
one.

**Comment by TehSeph** [comment]
^ this. The latest version on the repo does all the same things @Maytch's does aside from the completion text.

**Comment by Wolf1030** [comment]
I get ya, but they were both working just fine together last night. I removed one and tried the other and vice verca. So in each of my test, I only had one or the other on. Both cause it to not load. I am using Fiote Addonloader instead of yours which has been working so far with no issues.

**Comment by TehSeph** [comment]
It's not an issue with Fiote's loader either. I'm using that as well.

**Comment by Wolf1030** [comment]
Then I am not sure where the problem lays. As neither work together now or alone.

**Comment by TehSeph** [comment]
What other addons do you have? Could be another one hooking into the same place.

**Comment by Wolf1030** [comment]
just Fiote's, Exrulon, and LKchat's which is working right now. I also removed that one in my testing too to make sure.

**Comment by Excrulon** [comment]
Delete everything and reinstall I guess.

**Comment by TehSeph** [comment]
I don't think LKChat would cause a problem with this, but yeah reinstall them all.

**Comment by Wolf1030** [comment]
oh god I just feel silly now...ok it's gonna make me look REALLY nubish and retarded...instead of using my svn that I set up with the mods to pull updates from, in my 4am being up over 18 hrs haze, I didn't do that this morning. I right click and saved as on the mapfog update file which caused it to to look like this in the lua [http://pastebin.com/gMQmuzpk](url) sigh...issue resolved XD

Feel free to shame me now!

**Comment by Excrulon** [comment]
Shame shame shame! ;)
