### ISSUE TITLE
MapFogViewer main map scaling fog tiles with minimap zoom

### ISSUE THREAD

**Issue by alexms96** [Excrulon/Tree-of-Savior-Lua-Mods#62]
Using all files off the master branch, only exception is using Fiote's addonloader.

The fog tiles on the main map are scaling up and down with the minimap's zoom level, this seems to have originated after the commit fixing the minimap's tiles only being correct for 1.0x zoom.

[Minimap at .4x zoom](http://i.imgur.com/jQwETLA.jpg)

[Minimap at 2.4x zoom](http://i.imgur.com/ZmvtaDT.jpg)

EDIT: tested with your loader, clean addon folder and new sumani.ipf with same result

**Comment by Excrulon** [comment]
Oh, so they are, aren't they? Believe I know how to fix it, will do it after I finish my current backlog...

**Comment by TehSeph** [comment]
Oops. My bad. Forgot to test that. Should be a super simple fix.
@Excrulon Want me to fix and make a PR, or you got it?

**Comment by Excrulon** [comment]
Would be great if you did it, almost done with another addon currently. :smile:
