### ISSUE TITLE
Boss frame bugs

### ISSUE THREAD

**Issue by Crevox** [Excrulon/Tree-of-Savior-Lua-Mods#64]
A little glitchy. Replacing the health to that of the enemy I am fighting around here sometimes.

![image](https://cloud.githubusercontent.com/assets/6427024/14907450/e2d2620a-0d8e-11e6-9aab-dd5f34f22927.png)

**Comment by Crevox** [comment]
Also, any reason the size doesn't show on regular monsters?

**Comment by Excrulon** [comment]
Geeze you guys always pulling down changes right when I commit it, haha.

Hmm will have to look into that. Simply forgot to add size to the regular mobs again, will do that.

**Comment by Crevox** [comment]
Yeah, I totally sniped that commit, sorry. :) I just decided to check if there were any updates and yep!

**Comment by Excrulon** [comment]
It's a good thing, that's a bug I didn't know about. Earlier I saw the boss randomly changing data. With your post, I just now realized it's because it had stationary minions beside it. Hopefully it's fixable.

**Comment by Excrulon** [comment]
You've killed 16,000 siaulav mages...? lol.

**Comment by Crevox** [comment]
It's doing the same with the icons too, might've also seen it change to icons that shouldn't be anything around here (beasts). Also not sure what the... hit icon is supposed to mean next to size (weakness? mob damage type?)

And yes, I did. Where is my monster gem... :| :| :|

**Comment by Excrulon** [comment]
It's race, attribute, armor, moving/flying/stationary, attack weakness (strike/pierce/slash), size.

Makes sense that it'd do it for the icons too.

**Comment by Crevox** [comment]
Ah, that makes sense. Not sure if you were assuming people would infer that from the armor type or something. Showing the weakness is nice though, I still don't remember them very well. Still have a hard time discerning the armor types on these icons too (not that it's anything bugged or wrong with the addon).

**Comment by TehSeph** [comment]
> Geeze you guys always pulling down changes right when I commit it, haha.

I quite literally have the repo git checkout'd in my ToS folder. :stuck_out_tongue:

**Comment by Crevox** [comment]
That sounds like a plan...... :)

**Comment by Excrulon** [comment]
Well, my plan is to display more verbose text as an option or tooltips that show what each thing is and its weakness when you hover it.

**Comment by Grillo-del-mal** [comment]
Isn't "attack weakness" redundant since you already know it's armor type? 

Seeing the icon I thought that it meant the type of damage their normal attacks made

**Comment by Excrulon** [comment]
Maybe. I like it. Perhaps options to set what you want to see... some day. :wink:
