### ISSUE TITLE
ExpViewer  disappears when changing instantiates

### ISSUE THREAD

**Issue by mostarda17** [Excrulon/Tree-of-Savior-Lua-Mods#69]
It disappears when changing map or use some kind of teleportation .

Problems started to occur after you install the new version.

Thank you.

https://github.com/Excrulon/Tree-of-Savior-Lua-Mods/archive/master.zip

**Comment by iBaer** [comment]
https://github.com/Excrulon/Tree-of-Savior-Lua-Mods/issues/61

Temp fix: Use master version with official release version of the expviewer.
