### ISSUE TITLE
AddOn not appearing

### ISSUE THREAD

**Issue by wismanelli** [Excrulon/Tree-of-Savior-Lua-Mods#75]
Reinstalled ToS and replaced Addons + Data folders, "Load Addons" didn't work. It used to work before I uninstalled ToS. Any idea?

**Comment by Excrulon** [comment]
probably forgot to add my SumAni ipf to the data folder.

**Comment by wismanelli** [comment]
Hahaha okay this thread can be closed. Apparently I have been putting the file into an entirely different steam folder. Had to check Steam>TOS>Manage Local Files to find out that it is another directory. AKA had another dud ToS that didnt uninstall (I guess)
