### ISSUE TITLE
Monster Kill Tracker not working anymore

### ISSUE THREAD

**Issue by nsgalea** [Excrulon/Tree-of-Savior-Lua-Mods#77]
I installed the add-on today, at first it was working, then I went to town/re-logged, and when I came back it was no longer showing me kills.  Is there any way to figure out why it is no longer showing?

**Comment by dothuraka** [comment]
Same is happening for me.

Mods by:
Fiote
Excrulon
LemonKing
Miei
WatchGintama

Addon list:
betterquest
blockandreport
cabinetcommas
channelsurfer
cwapi
cwcleric
cwfarmed
cwshakeness
cwtolearn
expviewer
fixchatcontextmenu
guildmates
journalexport
lkchat - happens with both lua or ipf
mapfogviewer
monsterframes
monstertracker
removefpscounter
removemapbackground
removepetinfo
reportblock
showinvestedstatpoints
toggleduels

---Main
addonloader.lua
JSON.lua
utility.lua

With Excrulon SumAni.ipf installed.

**Comment by dothuraka** [comment]
Also, noticed that journalexport DOES NOT create journal-drops.JSON file.

**Comment by TehSeph** [comment]
@dothuraka `fixchatcontextmenu` has conflicts with `blockandreport`, and `LKChat` has conflicts with WatchGintama's minimap fog (but this functionality now exists in the repo version of Excrulon's so no need for both)

@nsgalea Do you have any other addons installed? Are you on the latest repo versions of the addons?

**Comment by dothuraka** [comment]
I've removed already WatchGintama's map fog, just write but forgot, also, it worked with ipf LKChat, just not with LUA due to the use of FPS_ON_MSG.
Did not know fixchatcontextmenu with blockandreport will fix.

Also, could it not be that any other plugin is also using FPS_ON_MSG parameters and one is nullifying each other?

**Comment by TehSeph** [comment]
`reportblock` might also be conflicting with `blockandreport` and `fixchatcontextmenu`, though not 100% sure on this one. I haven't looked at `reportblock`'s code, but the name alone sounds like it could conflict.

**Comment by dothuraka** [comment]
Searched and found out that now only Monster Tracker is using FPS_ON_MSG parameters.

Is it somehow configured to work with journal export (which is not really working - creating .JSON file)?

**Comment by TehSeph** [comment]
`journalexport` doesn't use `FPS_ON_MSG` and shouldn't be messing with the `monstertracker`.

**Comment by dothuraka** [comment]
My question was that if one wasn't supposed to work with each other.

**Comment by dothuraka** [comment]
It is kinda strange, but it only started happening after the last updates of the folder.

**Comment by TehSeph** [comment]
Nah, everything on this repo should work together fine. The conflict is coming from mixing repos which is normally fine but is an issue when two addons modify the same functions.

**Comment by nsgalea** [comment]
I have no other addons (apart from the ones included in the pack on this site).

It started working a bit ago for Vubbe Thief but not anything else, and just now after I opened the journal to double check Jukopus (which wasn't working), I killed a Jukopus and it worked.  I am not sure why it stopped, but it seems to be working again now.

Before that I re-installed twice, and relogged 2-3 times but it was still not working. Not sure what made it suddenly start working again now.

**Comment by dothuraka** [comment]
Maybe hidemaxedattributes, guildmates or blockandreport (newer ones) or another plugin update from it (or even monster tracker own updates) caused a bug.

**Comment by dothuraka** [comment]
Actually I do create plugin packages for my guild, @TehSeph. In the last week everything was working. Something (a lot of things) changed that made it start bugging.

**Comment by Excrulon** [comment]
Not really an issue with this addon pack as it works fine if installed on its own.

**Comment by TehSeph** [comment]
I'm currently using the latest github repo versions of
- betterquests
- blockandreport
- cabinetcommas
- channelsurfer
- cwapi
- expviewer
- guildmates
- hidemaxedattributes
- journalexport
- mapfogviewer
- monsterframes
- monstertracker
- removepetcommand
- removepetinfo
- showinvestedstatpoints
- toggleduels
So your issue isn't coming from any of those listed. Again, please check your addons for conflicts by adding them one-at-a-time. The issue isn't with the `monstertracker` addon itself.

**Comment by dothuraka** [comment]
Are you using all CW plugins?

I'll check and report.

**Comment by TehSeph** [comment]
Nope. Just cwapi as it's needed for fiote's addonloader. I had cwcleric and cwfarmed installed at one point so those should be fine. Don't know about his others.

**Comment by dothuraka** [comment]
Ok. Perfect.

Also, @TehSeph, is there any documentation for creating plugins?

**Comment by TehSeph** [comment]
Just https://github.com/Tree-of-Savior-Addon-Community/Addon-Tutorial/wiki
Most of us have learned just by reading the existing addons and browsing the official ipf files.

**Comment by dothuraka** [comment]
Removed CW To Learn
FixChatContextMenu
RemoveFPSCounter
RemoveMapBackground
RemoveWatermark

Now working as it should.

Will check which plugin is causing the bug.

**Comment by dothuraka** [comment]
Problem was due to FixChatContextMenu.

Else, all working normally.

**Comment by Excrulon** [comment]
> @dothuraka fixchatcontextmenu has conflicts with blockandreport

hours ago.
