### ISSUE TITLE
Lost the load addon button,

### ISSUE THREAD

**Issue by ChuangC** [Excrulon/Tree-of-Savior-Lua-Mods#78]
After a patch on monday, I lose the ability to press the load addon button.
Now, I can't load the addons anymore.

I try reinstall by delete the addons folder and SumAni.ipf. And try install fresh, it still doesn't show up.

Note: in the new zip file, I don't see anymore SumAni.ipf anymore.

Any helps? Thanks

**Comment by Excrulon** [comment]
downloaded wrong file. SumAni.ipf is inside https://github.com/Excrulon/Tree-of-Savior-Lua-Mods/releases/download/1.7/tos-lua-addons-excrulon-20160411-02.zip

**Comment by ChuangC** [comment]
THANK SO MUCH, I think i screw up a lot of files that's why I lost that's one.
FIXED.
Let me know if you have donation page, I can donate you a cup of coffee or something for your nice work.
