### ISSUE TITLE
New encryption method / single crash?

### ISSUE THREAD

**Issue by xjonsson** [Excrulon/Tree-of-Savior-Lua-Mods#8]
Hey Excrulon,

I was just wondering how you were compressing this to .ipf since on first launch with your SumAni.ipf it gives a crash saying that the files not vaild but on second run it works fine. Is this because you are using an older version of SumAni.ipf to inject into (non encrypted from previous build) and then it encrypts it with the new patcher or are you using new encrypted SumAni.ipf from IMC? Just curious since i was looking to help expand this module after seeing your silver counter =]

All the best,
Nick

**Comment by Excrulon** [comment]
It crashing has nothing to do with my SumAni.ipf file. Coincidence. It's not an old ipf.

I already have silver gained and silver/hour implemented, just have to clean it up for release.
