### ISSUE TITLE
Can not remove LOAD ADDON

### ISSUE THREAD

**Issue by petomcop13** [Excrulon/Tree-of-Savior-Lua-Mods#81]
when i click load addon it will not dissapear, how to fix it?

**Comment by fiote** [comment]
It probably means one of your addons are is loading correctly. If you're using [my loader](https://github.com/fiote/treeofsavior-addons), you can edit the addonloader.lua and set the debugLoading variable to true (line 9, probably). 

That will display some extra messages on the loading process, something like this:
"Opening addon folders..."
"addonA"
"addonB"
"addonC", etc etc

The last addon name that shows is probably the one at fault.

**Comment by AguaMolhada** [comment]
the Latest commit 89afac8  stoped working the addonloader. Only load until the hidemaxedattributes

**Comment by fiote** [comment]
@AguaMolhada and @petomcop13, I just download all Exclulon and my files, put them together (mines after so my addonloader stays) and it worked nice. Are you using any addons from other places?

Ps: I download the files ("Download zip" button), not the releases.

**Comment by Excrulon** [comment]
oh, remove dofile journal export from addon loader. need to commit that
when I get home. removed it because data isn't really accurate sadly.

**Comment by Excrulon** [comment]
Will add an updated version of it back this weekend.

**Comment by petomcop13** [comment]
I do not know why for my notebook it's pretty well but on the pc have problem cannot remove load addon on the center of monitor.

**Comment by AguaMolhada** [comment]
i`m using only this addon but i have found the same solution removing the dofile journalexport.lua 
petomcop13 open the addonoader.lua and "dofile("../addons/journalexport/journalexport.lua");"

**Comment by petomcop13** [comment]
Thank you all. it is work
