### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by ketok** [Excrulon/Tree-of-Savior-Lua-Mods#82]
Hello, I followed the instructions on unzip file etc , but it seems addon doesnt work for me.
I did not see any load addon on my screen.
Is there something that i should know on how to load these addons?

Thank you!

**Comment by alexcoliveira1** [comment]
Have you downloaded the "Release zip pack" that contains the "data" folder? 
1) Go to https://github.com/Excrulon/Tree-of-Savior-Lua-Mods/releases
2) Download tos-lua-addons-excrulon-20160411-02.zip (or latest). This zip contains the "data" folder that you need, the rest can be deleted.
3) Go to https://github.com/Excrulon/Tree-of-Savior-Lua-Mods
4) Click "Download ZIP". This will have the folder "addons"(may have more folders in the future, but for now it is only this one).
5) Copy it side-by-side with the "data" folder.
6) Copy them both to your ToS root folder, normally "C:\Program Files\Steam\steamapps\common\TreeOfSavior"

**Comment by TehSeph** [comment]
If you use the instructions above, you'll also need to edit the `addonloader.lua` file and remove the line
```
dofile("../addons/journalexport/journalexport.lua");
```
since that addon has been removed from the repo and this change was forgotten. @Excrulon should be making a new release soon-ish that will be more up to date with the repo and possibly remove the need for the SumAni.ipf file

**Comment by ketok** [comment]
thank you guys for your fast reply!
it works perfectly now .
thank you!

**Comment by TehSeph** [comment]
@ketok Glad to hear. Go ahead and close the issue so Excrulon doesn't have to read this when it's already been solved. :smile:
