### ISSUE TITLE
Load Addons button doesn't disappear

### ISSUE THREAD

**Issue by gengar2757** [Excrulon/Tree-of-Savior-Lua-Mods#92]
I'm sorry if it's a problem with a solution in plain sight, but my Load Addons button doesn't disappear after clicking it

**Comment by solbisio** [comment]
same here.

**Comment by Cygote** [comment]
I also have this problem.

**Comment by Excrulon** [comment]
use clean install, should work fine. make sure expcardcalculator.ipf still
has a unicode character in it after extracting it to data folder.

**Comment by gengar2757** [comment]
Sorry, what do you mean by clean install? Also, I can't find an expcardcalculator.ipf. The only ones i can find is expcardcalculator.lua and expcardcalculator.xml

**Comment by gengar2757** [comment]
ah I found the expcardcalculator.ipf in the zip file, but I dont know how to place the unicode character in it..

**Comment by pedrosotero** [comment]
same here, clean install from release

**Comment by Excrulon** [comment]
yes, extract everything.

☃expcardcalculator.ipf

That ipf should be named like that after being extracted. Majority of the time it should be fine but  supposedly some versions of Windows or something can corrupt that character and you'll have to manually replace it.

**Comment by Karakato** [comment]
Hey Excrulon, i am experiencing the same problem too.
i do not see any ☃expcardcalculator.ipf in the zip that i have extracted from. 
and sorry, what do you mean by clean install? thanks!

**Comment by Excrulon** [comment]
It is in the zip. I just don't understand how everyone isn't seeing it.
Extract the whole zip to tos directory.

**Comment by Karakato** [comment]
ah, okay, got it. thanks Excrulon
