### ISSUE TITLE
Card calculator reapeating data

### ISSUE THREAD

**Issue by pedrosotero** [Excrulon/Tree-of-Savior-Lua-Mods#95]
![image](https://cloud.githubusercontent.com/assets/11163132/15179842/7c911e58-1754-11e6-8ac9-4022681e9cfe.png)

First, the idea about this addon is amazing congrats ! i know this is a unstable version but i found this issue, when i got a new card this thing adds all the other cards again in the list

**Comment by Excrulon** [comment]
ah yeah saw that but didn't know what triggered it. it's just a visual bug.
the calculated level is still accurate. will fix soon.

**Comment by Crevox** [comment]
My calculation is wrong. Card calculator says I will be level 238, but I would only be level 235.

![image](https://cloud.githubusercontent.com/assets/6427024/15200653/6b5c80c8-17ae-11e6-8abc-2844e4017a58.png)

**Comment by Excrulon** [comment]
Sounds like a separate issue if true.

This one is fixed with 050f935ffb73fd9d8595fcedf5643164c516120f.
