### ISSUE TITLE
Add .editorconfig ?

### ISSUE THREAD

**Issue by zckrs** [Excrulon/Tree-of-Savior-Lua-Mods#97]
http://editorconfig.org/

EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs. 
The EditorConfig project consists of a file format for defining coding styles and a collection of text editor plugins that enable editors to read the file format and adhere to defined styles. 
EditorConfig files are easily readable and they work nicely with version control systems.

Example plugins for some IDE:
* https://atom.io/packages/editorconfig
* https://github.com/editorconfig/editorconfig-vscode
* https://github.com/sindresorhus/editorconfig-sublime

**Comment by Excrulon** [comment]
Will this only work if people are using an editor that supports this? Will it force anyone making commits against this project to have tabs if it's set to that? Not really sure what is gained from it after reading the page.

**Comment by zckrs** [comment]
I never seen a IDE who dont have a plugin for editorconfig (Notepad++ have too) 

True that will never force contributor to respect theses conventions. But if we have plugins already installed Editorconfig aims to configure EOL and indent style per project.

What do you use initially on .lua files? 
* Tabs ?
* LF ?

**Comment by zckrs** [comment]
[IDE supported](http://editorconfig.org/#download)

**Comment by TehSeph** [comment]
>I never seen a IDE who dont have a plugin for editorconfig

But the point is, people need to get the plugin. Otherwise this is useless. People will still need to use an IDE that supports it and install the plugin, and a lot of them won't even bother. It won't hurt anything to add an `.editorconfig` file to the repo, but it's not some magic fix either.

**Comment by zckrs** [comment]
@TehSeph 

True but this solution can be helpful comparing to nothing.

This is just a proposal. I see several times in this repository PR are difficult to review

**Comment by TehSeph** [comment]
Yeah it's not a bad suggestion. Just saying, it's not a solution either.

**Comment by zckrs** [comment]
LUA used 2 spaces for indentation right ?

**Comment by Excrulon** [comment]
Tabs for indention. Always tabs!

**Comment by zckrs** [comment]
No problem but why ? technical issue ?

From http://lua-users.org/wiki/LuaStyleGuide

>Indentation - Indenting often uses two spaces. This is followed in Programming in Lua, the Lua Reference Manual, Beginning Lua Programming, and the Lua users wiki.

**Comment by TehSeph** [comment]
Because 2 spaces is too little for a lot of people's tastes, and tab sizes can be adjusted to any lenght the user wants it to be.

**Comment by zckrs** [comment]
> can be adjusted to any lenght the user wants it to be

:+1: 

If you merge #98 I can fix on existing file:
* indent to TAB
* eol to LF
* use beautifier ?

**Comment by Excrulon** [comment]
Spaces are disgusting. Tabs are an abstraction for space. They can easily represent any amount of space you want. That's all. Plus it's way more annoying to navigate code with arrows when there are spaces and I hate random spaces all throughout my code. Any style guide that says to use spaces or projects that use spaces are simply wrong. This isn't opinion, it's fact. This is the holy war that has been debated since programming was a thing. I feel very strongly about this subject, also not going to debate it any. Haha.

This sums it up very nicely.

http://www.rizzoweb.com/java/tabs-vs-spaces.html
